# Generated by Django 4.1.3 on 2022-11-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exp', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Date_Debut', models.DateField()),
                ('Date_Fini', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.SlugField(max_length=20)),
                ('Password', models.SlugField(max_length=20)),
                ('Role', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id_Just', models.BigAutoField(primary_key=True, serialize=False)),
                ('Fichier', models.BinaryField()),
                ('id_Experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entities.experience')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=30)),
                ('DescPro', models.TextField()),
                ('Philo_Statement', models.TextField()),
                ('Bio', models.TextField()),
                ('id_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entities.person')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='id_Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entities.person'),
        ),
    ]
