# Generated by Django 4.1.3 on 2022-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopers',
            name='birthDate',
            field=models.DateField(default='2022-12-11'),
        ),
        migrations.AddField(
            model_name='infopers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='infopers',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='infopers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='Fichier',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='Login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
