# Generated by Django 4.1.3 on 2022-12-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0002_infopers_birthdate_infopers_email_infopers_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Login',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Password',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
