# Generated by Django 4.1.3 on 2022-12-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0003_alter_person_login_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default='roudeina', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Type',
            field=models.CharField(choices=[('P', 'Professionel'), ('A', 'Associatif'), ('R', 'Recompense')], default='F', max_length=10),
        ),
    ]
