# Generated by Django 4.1.3 on 2022-12-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0004_experience_name_alter_experience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
