# Generated by Django 4.1.3 on 2022-12-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0005_alter_experience_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='name',
            field=models.CharField(default='roudeina', max_length=50),
        ),
    ]
