# Generated by Django 4.1.3 on 2022-12-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0006_justification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
